---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cloudbeaver.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.cloudbeaver.name }}
  ports:
    - port: {{ .Values.cloudbeaver.service.port }}
      targetPort: {{ .Values.cloudbeaver.deployment.containerPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cloudbeaver.name }}
  labels:
    app: {{ .Values.cloudbeaver.name }}
spec:
  replicas: {{ .Values.cloudbeaver.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.cloudbeaver.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.cloudbeaver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cloudbeaver.name }}
    spec:
      containers:
        - name: {{ .Values.cloudbeaver.name }}
          image: {{ .Values.cloudbeaver.deployment.image }}
          ports:
            - name: http
              containerPort: {{ .Values.cloudbeaver.deployment.containerPort }}
          imagePullPolicy: {{ .Values.cloudbeaver.deployment.imagePullPolicy }}
