---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    app: {{ .Values.keycloak.name }}
spec:
  replicas: {{ .Values.keycloak.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.keycloak.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.keycloak.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.keycloak.name }}
        keycloak-cluster: {{ .Values.keycloak.cluster.kube_ping_label_value }}
    spec:
      serviceAccountName: {{ .Values.keycloak.name }}
      containers:
        - name: {{ .Values.keycloak.name }}
          image: {{ .Values.keycloak.deployment.image }}
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.deployment.containerPort }}
          command: 
            - /bin/bash
            - -c
            - /opt/keycloak/bin/kc.sh --verbose start --spi-events-listener-jboss-logging-success-level=info --spi-events-listener-jboss-logging-error-level=warn
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.env.admin }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.env.adminPassword }}
            - name: KC_HOSTNAME_URL
              value: {{ .Values.keycloak.env.hostnameUrl }}
            - name: KC_HOSTNAME_ADMIN_URL
              value: {{ .Values.keycloak.env.hostnameAdminUrl }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .Values.keycloak.env.hostnameStrict | quote }}
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: {{ .Values.keycloak.env.hostnameStrictHttps | quote }}
            - name: KC_HTTP_ENABLED
              value: {{ .Values.keycloak.env.httpEnabled | quote }}
            - name: KC_PROXY
              value: {{ .Values.keycloak.env.proxy | quote }}
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_CACHE_CONFIG_FILE
              value: cache-ispn-kubeping.xml
            - name: JAVA_OPTS_APPEND
              value: >-
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=50.0
                -Djava.awt.headless=true
                -Dkubeping_namespace={{ .Release.Namespace }}
                -Dkubeping_label="keycloak-cluster={{ .Values.keycloak.cluster.kube_ping_label_value }}"
            - name: KC_DB
              value: {{ .Values.keycloak.env.db }}
            - name: KC_DB_URL
              value: {{ .Values.keycloak.env.dbUrl }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.env.dbUsername }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.env.dbPassword }}
            - name: USER_DB_URL
              value: {{ .Values.keycloak.env.userDbUrl }}
            - name: USER_DB_USERNAME
              value: {{ .Values.keycloak.env.userDbUsername }}
            - name: USER_DB_PASSWORD
              value: {{ .Values.keycloak.env.userDbPassword }}
          imagePullPolicy: {{ .Values.keycloak.deployment.imagePullPolicy }}
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.keycloak.deployment.containerPort }}
            initialDelaySeconds: 60 
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.keycloak.deployment.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.keycloak.deployment.containerPort }}
            failureThreshold: 30
            periodSeconds: 10
