---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.keycloak.name }}
  annotations:
    # Resolves the following controller error: 'upstream sent too big header while reading response header from upstream'
    nginx.org/proxy-buffer-size: 8k
spec:
  rules:
    - host: {{ .Values.keycloak.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.name }}
                port:
                  number: {{ .Values.keycloak.service.port }}
  ingressClassName: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.keycloak.name }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: {{ .Values.keycloak.deployment.containerPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    app: {{ .Values.keycloak.name }}
spec:
  replicas: {{ .Values.keycloak.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.keycloak.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.keycloak.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.keycloak.name }}
    spec:
      containers:
        - name: {{ .Values.keycloak.name }}
          image: {{ .Values.keycloak.deployment.image }}
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.deployment.containerPort }}
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.env.admin }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.env.adminPassword }}
            - name: KC_HOSTNAME_URL
              value: {{ .Values.keycloak.env.hostnameUrl }}
            - name: KC_HOSTNAME_ADMIN_URL
              value: {{ .Values.keycloak.env.hostnameAdminUrl }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .Values.keycloak.env.hostnameStrict | quote }}
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: {{ .Values.keycloak.env.hostnameStrictHttps | quote }}
            - name: KC_HTTP_ENABLED
              value: {{ .Values.keycloak.env.httpEnabled | quote }}
            - name: KC_PROXY
              value: {{ .Values.keycloak.env.proxy | quote }}
            - name: KC_DB
              value: {{ .Values.keycloak.env.db }}
            - name: KC_DB_URL
              value: {{ .Values.keycloak.env.dbUrl }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.env.dbUsername }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.env.dbPassword }}
          imagePullPolicy: {{ .Values.keycloak.deployment.imagePullPolicy }}
