---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-pod-reader-{{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jgroups-kubeping-api-access-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-kubeping-pod-reader-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: {{ .Release.Namespace }}
