---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.keycloak.name }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: {{ .Values.keycloak.deployment.containerPort }}


