keycloak:
  name: keycloak

  ingress:
    host: zero.codurance.io

  service:
    port: 80

  deployment:
    image: 300563897675.dkr.ecr.eu-central-1.amazonaws.com/dev-zero-ecr:1.0.13
    replicas: 1
    revisionHistoryLimit: 2
    containerPort: 8080
    imagePullPolicy: IfNotPresent

  env:
    admin: admin
    adminPassword: password
    hostnameUrl: https://zero.codurance.io
    hostnameAdminUrl: https://zero.codurance.io
    hostnameStrict: "false"
    hostnameStrictHttps: "false"
    httpEnabled: "true"
    proxy: "edge"
    db: mysql
    dbUrl: jdbc:mysql://mysql.keycloak.svc.cluster.local:3306/db
    dbUsername: admin
    dbPassword: password
    userDbUrl: jdbc:mysql://mysql2.keycloak.svc.cluster.local:3306/db
    userDbUsername: admin
    userDbPassword: password

  cluster:
    kube_ping_label_value: default

mysql:
  name: mysql

  service:
    port: 3306

  deployment:
    image: mysql:8.0.32
    replicas: 1
    revisionHistoryLimit: 2
    containerPort: 3306
    imagePullPolicy: IfNotPresent

  env:
    database: db
    user: admin
    password: password
    rootPassword: password

mysql2:
  name: mysql2

  service:
    port: 3306

  deployment:
    image: mysql:8.0.32
    replicas: 1
    revisionHistoryLimit: 2
    containerPort: 3306
    imagePullPolicy: IfNotPresent

  env:
    database: db
    user: admin
    password: password
    rootPassword: password

cloudbeaver:
  name: cloudbeaver

  service:
    port: 80

  deployment:
    image: dbeaver/cloudbeaver:22.3.3
    replicas: 1
    revisionHistoryLimit: 2
    containerPort: 8978
    imagePullPolicy: IfNotPresent
