version: "3.9"

services:

  app:
    build: .
    image: app
    container_name: app
    ports:
      - 8080:80
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: psql -v ON_ERROR_STOP=1 -U "admin" -d "db" -c 'SELECT * FROM users;'
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:6.19
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
